M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-06-11T15:19:33+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-11T15:19:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T2
X27.4Y-46.5
T1
G00X23.0Y-46.75
M15
G01X23.0Y-46.25
M16
G05
M30
