M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-06-11T15:11:59+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-11T15:11:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X18.5Y-18.5
X18.5Y-41.5
X76.5Y-18.5
X76.5Y-41.5
M30
