# Generated by Django 6.1 on 2026-08-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('solde_analytique', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_operationnel', models.BooleanField(default=True, help_text="Décoche pour un pôle qui n'a pas son propre point de vente (ex. ADE, qui vend sous BDE) : il disparaît des listes de vente et de gestion, mais le rôle Admin ADE reste intact et continue de superviser les autres pôles.")),
                ('logo', models.ImageField(blank=True, help_text='Logo affiché sur les listes de pôles (adhésion, etc.). Optionnel.', null=True, upload_to='poles/')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='evenements/')),
                ('actif', models.BooleanField(default=True)),
                ('date_fin_vente', models.DateTimeField(blank=True, help_text="À partir de cette date et heure, plus rien ne peut être vendu pour cet événement, même si 'actif' reste coché. Laisser vide pour ne pas fixer de coupure automatique.", null=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='caisse.pole')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='caisse.pole')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('disponible', models.BooleanField(default=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('est_billet', models.BooleanField(default=True, help_text='Uniquement pour un produit rattaché à un événement : coché si ce produit représente une entrée (compte dans la liste des participants et se synchronise avec HelloAsso), décoché pour un produit du catalogue de la soirée (boisson, écocup...) qui ne compte pas comme une présence.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('est_vente_libre', models.BooleanField(default=False, editable=False, help_text='Produit technique utilisé par le terminal (montant libre), jamais affiché dans le catalogue.')),
                ('retire', models.BooleanField(default=False, help_text='Produit qui n\'est plus vendu du tout : disparaît de la vente et de la gestion normale, déplacé dans l\'onglet "Retirés" (visible uniquement des admins, jamais des vendeurs). Différent de "Disponible", qui reste visible mais grisé sur l\'écran de vente.')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='caisse.categorie')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='caisse.evenement')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='caisse.pole')),
            ],
        ),
    ]
