# Generated by Django 6.1 on 2026-08-24 09:28

import caisse.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VENDEUR', 'Vendeur'), ('ADMIN_POLE', 'Admin de pôle'), ('ADMIN_ADE', 'Admin ADE'), ('ADMIN_ECOLE', 'Admin école')], max_length=20)),
                ('droit_recharger_especes', models.BooleanField(default=False)),
                ('droit_adhesion_especes', models.BooleanField(default=False)),
                ('droit_gerer_produits', models.BooleanField(default=False)),
                ('droit_adhesions', models.BooleanField(default=False)),
                ('droit_equipe', models.BooleanField(default=False, help_text="Voir l'onglet Equipe (qui a quels droits). N'autorise jamais a modifier les droits de qui que ce soit : cette action reste toujours reservee aux admins.")),
                ('droit_exporter', models.BooleanField(default=False)),
                ('droit_parametres', models.BooleanField(default=False)),
                ('pole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='caisse.pole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantImporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_importes', to='caisse.evenement')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('uid_rfid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('secret_qr', models.CharField(default=caisse.models.generer_secret_qr, max_length=64)),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('DESACTIVE', 'Désactivé'), ('ANONYMISE', 'Anonymisé')], default='ACTIF', max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JetonPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=caisse.models.generer_code_jeton, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='caisse.profilutilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeSuppressionCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('remboursement_effectue', models.BooleanField(default=False, help_text="Coché par l'admin école une fois le remboursement du solde géré en dehors de l'application.")),
                ('demande_par', models.ForeignKey(help_text="L'admin école qui a déclenché cette demande de suppression.", on_delete=django.db.models.deletion.PROTECT, related_name='suppressions_demandees', to=settings.AUTH_USER_MODEL)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_suppression', to='caisse.profilutilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ECHOUEE', 'Échouée')], default='EN_ATTENTE', max_length=10)),
                ('reference_helloasso', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(choices=[('HELLOASSO', 'HelloAsso'), ('ESPECES', 'Espèces')], default='HELLOASSO', max_length=12)),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recharges_encaissees', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(blank=True, help_text="Le pôle depuis lequel la recharge a été faite (uniquement pour les recharges en espèces ; une recharge HelloAsso n'est rattachée à aucun pôle en particulier).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recharges_especes', to='caisse.pole')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharges', to='caisse.profilutilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='TarifAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Ce que l'etudiant lit pour choisir, ex. '1ere annee' ou 'Ancien eleve'.", max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_adhesion', to='caisse.pole')),
            ],
            options={
                'verbose_name': "tarif d'adhésion",
                'ordering': ['prix'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='caisse.pole')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='caisse.profilutilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('reference_helloasso', models.CharField(blank=True, help_text="Renseignée automatiquement si ce billet a été poussé vers une inscription HelloAsso au moment de l'achat.", max_length=100)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='caisse.produit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='caisse.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSecuriteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('definie_par', models.ForeignKey(help_text="L'admin école qui a généré ce code.", on_delete=django.db.models.deletion.PROTECT, related_name='codes_definis', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(blank=True, help_text='Le pôle concerné. Vide pour un admin ADE (portée globale).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_securite', to='caisse.pole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_securite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code de sécurité admin',
                'unique_together': {('user', 'pole')},
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(help_text="Année de début de l'année scolaire, ex. 2026 pour 2026-2027.")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mode_paiement', models.CharField(choices=[('PORTEFEUILLE', 'Portefeuille'), ('ESPECES', 'Espèces')], default='PORTEFEUILLE', max_length=12)),
                ('reference_helloasso', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adhesions_encaissees', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='caisse.pole')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='caisse.profilutilisateur')),
            ],
            options={
                'verbose_name': 'adhésion',
                'unique_together': {('pole', 'profil', 'annee')},
            },
        ),
    ]
