from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from . import vues_ecole

urlpatterns = [
    path("", views.accueil, name="accueil"),
    path("recharger/", views.recharger, name="recharger"),
    path("info/", views.info, name="info"),
    path("asso/", views.asso_choix, name="asso_choix"),
    path("pole/<slug:slug>/asso/", views.espace_asso, name="espace_asso"),
    path("pole/<slug:slug>/equipe/", views.equipe_pole, name="equipe_pole"),
    path("pole/<slug:slug>/export/", views.export_pole, name="export_pole"),
    path("outils/identifiant/", views.rechercher_identifiant, name="rechercher_identifiant"),
    path("terminal/", views.terminal_choix_pole, name="terminal_choix_pole"),
    path("pole/<slug:slug>/terminal/", views.terminal_pole, name="terminal_pole"),
    path("payer/", views.mon_qr, name="payer"),
    path("connexion/", auth_views.LoginView.as_view(template_name="caisse/login.html"), name="login"),
    path("deconnexion/", auth_views.LogoutView.as_view(), name="logout"),
    path("pole/<slug:slug>/", views.detail_pole, name="detail_pole"),
    path("ajouter/<int:produit_id>/", views.ajouter_au_panier, name="ajouter_au_panier"),
    path("pole/<slug:slug>/vider/", views.vider_panier, name="vider_panier"),
    path("pole/<slug:slug>/panier/", views.voir_panier, name="voir_panier"),
    path("pole/<slug:slug>/encaisser/", views.encaisser, name="encaisser"),
    path("pole/<slug:slug>/gerer/", views.gerer_produits, name="gerer_produits"),
    path("pole/<slug:slug>/gerer/categories/", views.gerer_categories, name="gerer_categories"),
    path("pole/<slug:slug>/gerer/categories/<int:categorie_id>/", views.modifier_categorie, name="modifier_categorie"),
    path("pole/<slug:slug>/gerer/nouveau/", views.creer_produit, name="creer_produit"),
    path("pole/<slug:slug>/gerer/<int:produit_id>/", views.modifier_produit, name="modifier_produit"),
    path("pole/<slug:slug>/gerer/evenements/", views.gerer_evenements, name="gerer_evenements"),
    path("pole/<slug:slug>/gerer/evenements/nouveau/", views.creer_evenement, name="creer_evenement"),
    path("pole/<slug:slug>/gerer/evenements/<int:evenement_id>/", views.modifier_evenement, name="modifier_evenement"),
    path("pole/<slug:slug>/gerer/evenements/<int:evenement_id>/billets/nouveau/", views.creer_billet, name="creer_billet"),
    path("pole/<slug:slug>/gerer/evenements/<int:evenement_id>/billets/<int:produit_id>/", views.modifier_billet, name="modifier_billet"),
    path("pole/<slug:slug>/gerer/evenements/<int:evenement_id>/participants/importer/", views.importer_participants, name="importer_participants"),
    path("pole/<slug:slug>/gerer/evenements/<int:evenement_id>/participants/export/", views.exporter_participants, name="exporter_participants"),
    path("pole/<slug:slug>/gerer/evenements/<int:evenement_id>/participants/", views.participants_evenement, name="participants_evenement"),
    path("adherer/", views.adherer_liste, name="adherer_liste"),
    path("pole/<slug:slug>/adherer/", views.adherer_pole, name="adherer_pole"),
    path("pole/<slug:slug>/gerer/adherents/", views.gerer_adherents, name="gerer_adherents"),
    path("pole/<slug:slug>/gerer/adherents/export/", views.exporter_adherents, name="exporter_adherents"),
    path("pole/<slug:slug>/especes/", views.recharger_especes, name="recharger_especes"),
    path("pole/<slug:slug>/adhesion/especes/", views.payer_adhesion_especes, name="payer_adhesion_especes"),
    path("pole/<slug:slug>/gerer/especes/", views.gerer_especes, name="gerer_especes"),
    path("pole/<slug:slug>/gerer/especes/export/", views.exporter_especes, name="exporter_especes"),
        path("pole/<slug:slug>/gerer/parametres/", views.modifier_pole, name="modifier_pole"),
    path("ecole/", vues_ecole.espace_ecole, name="espace_ecole"),
    path("ecole/equipe/", vues_ecole.ecole_equipe, name="ecole_equipe"),
    path("ecole/recettes/", vues_ecole.ecole_recettes, name="ecole_recettes"),
    path("ecole/adherents/", vues_ecole.ecole_adherents, name="ecole_adherents"),
    path("ecole/adherents/<slug:slug>/", vues_ecole.ecole_adherents_pole, name="ecole_adherents_pole"),
    path("ecole/profils/", vues_ecole.ecole_profils, name="ecole_profils"),
    path("ecole/codes/", vues_ecole.ecole_codes, name="ecole_codes"),
    path("ecole/comptes/", vues_ecole.ecole_comptes, name="ecole_comptes"),
    path("verifier-code/", vues_ecole.verifier_code, name="verifier_code"),
]
