# Generated by Django 6.0.7 on 2026-07-21 10:07

import caisse.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('uid_rfid', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('secret_qr', models.CharField(default=caisse.models.generer_secret_qr, max_length=64)),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('DESACTIVE', 'Desactive'), ('ANONYMISE', 'Anonymise')], default='ACTIF', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmee'), ('ECHOUEE', 'Echouee')], default='EN_ATTENTE', max_length=10)),
                ('reference_helloasso', models.CharField(blank=True, max_length=100, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharges', to='caisse.profilutilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='caisse.pole')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='caisse.profilutilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes', to='caisse.produit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='caisse.transaction')),
            ],
        ),
    ]
