# Generated by Django 6.0.7 on 2026-07-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_profilutilisateur_recharge_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
