# Generated by Django 6.0.7 on 2026-07-22 13:30

import caisse.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0004_affectation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetonPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=caisse.models.generer_code_jeton, max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilise', models.BooleanField(default=False)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons', to='caisse.profilutilisateur')),
            ],
        ),
    ]
