# Generated by Django 6.0.7 on 2026-07-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_jetonpaiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_vente_libre',
            field=models.BooleanField(default=False, editable=False, help_text='Produit technique utilise par le terminal (montant libre), jamais affiche dans le catalogue.'),
        ),
    ]
