# Generated by Django 6.0.7 on 2026-07-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_produit_est_vente_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='pseudo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
