# Generated by Django 6.0.7 on 2026-07-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_profilutilisateur_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
    ]
