# Generated by Django 6.0.7 on 2026-07-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0008_evenement_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantImporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('quantite', models.PositiveSmallIntegerField(default=1)),
                ('date_import', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_importes', to='caisse.evenement')),
            ],
        ),
    ]
