# Generated by Django 6.0.7 on 2026-07-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0009_participantimporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='lieu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
