# Generated by Django 6.0.7 on 2026-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0010_evenement_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignetransaction',
            name='reference_helloasso',
            field=models.CharField(blank=True, help_text="Renseignee automatiquement si ce billet a ete pousse vers une inscription HelloAsso au moment de l'achat.", max_length=100),
        ),
    ]
