# Generated by Django 6.0.7 on 2026-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0011_lignetransaction_reference_helloasso'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_billet',
            field=models.BooleanField(default=True, help_text='Uniquement pour un produit rattache a un evenement : coche si ce produit represente une entree (compte dans la liste des participants et se synchronise avec HelloAsso), decoche pour un produit du catalogue de la soiree (boisson, ecocup...) qui ne compte pas comme une presence.'),
        ),
    ]
