# Generated by Django 6.0.7 on 2026-07-24 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0012_produit_est_billet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='date_fin_vente',
            field=models.DateTimeField(blank=True, help_text="A partir de cette date et heure, plus rien ne peut etre vendu pour cet evenement, meme si 'actif' reste coche. Laisser vide pour ne pas fixer de coupure automatique.", null=True),
        ),
        migrations.AddField(
            model_name='pole',
            name='prix_adhesion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix de l'adhesion annuelle. Laisser vide si ce pole ne propose pas d'adhesion payante.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='recharge',
            name='encaisse_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recharges_encaissees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recharge',
            name='mode_paiement',
            field=models.CharField(choices=[('HELLOASSO', 'HelloAsso'), ('ESPECES', 'Especes')], default='HELLOASSO', max_length=12),
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(help_text="Annee de debut de l'annee scolaire, ex. 2026 pour 2026-2027.")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mode_paiement', models.CharField(choices=[('PORTEFEUILLE', 'Portefeuille'), ('ESPECES', 'Especes')], default='PORTEFEUILLE', max_length=12)),
                ('reference_helloasso', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adhesions_encaissees', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='caisse.pole')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adhesions', to='caisse.profilutilisateur')),
            ],
            options={
                'verbose_name': 'adhesion',
                'unique_together': {('pole', 'profil', 'annee')},
            },
        ),
    ]
