# Generated by Django 6.0.7 on 2026-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0013_evenement_date_fin_vente_pole_prix_adhesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo affiche sur les listes de poles (adhesion, etc.). Optionnel.', null=True, upload_to='poles/'),
        ),
    ]
