# Generated by Django 6.0.7 on 2026-08-17 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0014_pole_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='role',
            field=models.CharField(choices=[('VENDEUR', 'Vendeur'), ('ADMIN_POLE', 'Admin de pole'), ('ADMIN_ADE', 'Admin ADE'), ('ADMIN_ECOLE', 'Admin ecole')], max_length=20),
        ),
        migrations.CreateModel(
            name='CodeSecuriteAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('definie_par', models.ForeignKey(help_text="L'admin ecole qui a genere ce code.", on_delete=django.db.models.deletion.PROTECT, related_name='codes_definis', to=settings.AUTH_USER_MODEL)),
                ('pole', models.ForeignKey(blank=True, help_text='Le pole concerne. Vide pour un admin ADE (portee globale).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_securite', to='caisse.pole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_securite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'code de securite admin',
                'unique_together': {('user', 'pole')},
            },
        ),
    ]
