# Generated by Django 6.0.7 on 2026-08-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0015_alter_affectation_role_codesecuriteadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='pole',
            field=models.ForeignKey(blank=True, help_text="Le pole depuis lequel la recharge a ete faite (uniquement pour les recharges en especes ; une recharge HelloAsso n'est rattachee a aucun pole en particulier).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recharges_especes', to='caisse.pole'),
        ),
    ]
