# Generated by Django 6.0.7 on 2026-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0016_recharge_pole'),
    ]

    operations = [
        migrations.AddField(
            model_name='pole',
            name='est_operationnel',
            field=models.BooleanField(default=True, help_text="Decoche pour un pole qui n'a pas son propre point de vente (ex. ADE, qui vend sous BDE) : il disparait des listes de vente et de gestion, mais le role Admin ADE reste intact et continue de superviser les autres poles."),
        ),
    ]
