# Generated by Django 6.0.7 on 2026-08-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0017_pole_est_operationnel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhesion',
            options={'verbose_name': 'adhésion'},
        ),
        migrations.AlterModelOptions(
            name='codesecuriteadmin',
            options={'verbose_name': 'code de sécurité admin'},
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='annee',
            field=models.PositiveSmallIntegerField(help_text="Année de début de l'année scolaire, ex. 2026 pour 2026-2027."),
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='mode_paiement',
            field=models.CharField(choices=[('PORTEFEUILLE', 'Portefeuille'), ('ESPECES', 'Espèces')], default='PORTEFEUILLE', max_length=12),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='role',
            field=models.CharField(choices=[('VENDEUR', 'Vendeur'), ('ADMIN_POLE', 'Admin de pôle'), ('ADMIN_ADE', 'Admin ADE'), ('ADMIN_ECOLE', 'Admin école')], max_length=20),
        ),
        migrations.AlterField(
            model_name='codesecuriteadmin',
            name='definie_par',
            field=models.ForeignKey(help_text="L'admin école qui a généré ce code.", on_delete=django.db.models.deletion.PROTECT, related_name='codes_definis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codesecuriteadmin',
            name='pole',
            field=models.ForeignKey(blank=True, help_text='Le pôle concerné. Vide pour un admin ADE (portée globale).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes_securite', to='caisse.pole'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_fin_vente',
            field=models.DateTimeField(blank=True, help_text="À partir de cette date et heure, plus rien ne peut être vendu pour cet événement, même si 'actif' reste coché. Laisser vide pour ne pas fixer de coupure automatique.", null=True),
        ),
        migrations.AlterField(
            model_name='lignetransaction',
            name='reference_helloasso',
            field=models.CharField(blank=True, help_text="Renseignée automatiquement si ce billet a été poussé vers une inscription HelloAsso au moment de l'achat.", max_length=100),
        ),
        migrations.AlterField(
            model_name='pole',
            name='est_operationnel',
            field=models.BooleanField(default=True, help_text="Décoche pour un pôle qui n'a pas son propre point de vente (ex. ADE, qui vend sous BDE) : il disparaît des listes de vente et de gestion, mais le rôle Admin ADE reste intact et continue de superviser les autres pôles."),
        ),
        migrations.AlterField(
            model_name='pole',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo affiché sur les listes de pôles (adhésion, etc.). Optionnel.', null=True, upload_to='poles/'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='prix_adhesion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Prix de l'adhésion annuelle. Laisser vide si ce pôle ne propose pas d'adhésion payante.", max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='est_billet',
            field=models.BooleanField(default=True, help_text='Uniquement pour un produit rattaché à un événement : coché si ce produit représente une entrée (compte dans la liste des participants et se synchronise avec HelloAsso), décoché pour un produit du catalogue de la soirée (boisson, écocup...) qui ne compte pas comme une présence.'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='est_vente_libre',
            field=models.BooleanField(default=False, editable=False, help_text='Produit technique utilisé par le terminal (montant libre), jamais affiché dans le catalogue.'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='statut_compte',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('DESACTIVE', 'Désactivé'), ('ANONYMISE', 'Anonymisé')], default='ACTIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='mode_paiement',
            field=models.CharField(choices=[('HELLOASSO', 'HelloAsso'), ('ESPECES', 'Espèces')], default='HELLOASSO', max_length=12),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='pole',
            field=models.ForeignKey(blank=True, help_text="Le pôle depuis lequel la recharge a été faite (uniquement pour les recharges en espèces ; une recharge HelloAsso n'est rattachée à aucun pôle en particulier).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recharges_especes', to='caisse.pole'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ECHOUEE', 'Échouée')], default='EN_ATTENTE', max_length=10),
        ),
        migrations.CreateModel(
            name='DemandeSuppressionCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('remboursement_effectue', models.BooleanField(default=False, help_text="Coché par l'admin école une fois le remboursement du solde géré en dehors de l'application.")),
                ('demande_par', models.ForeignKey(help_text="L'admin école qui a déclenché cette demande de suppression.", on_delete=django.db.models.deletion.PROTECT, related_name='suppressions_demandees', to=settings.AUTH_USER_MODEL)),
                ('profil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_suppression', to='caisse.profilutilisateur')),
            ],
        ),
    ]
