# Generated by Django 6.0.7 on 2026-08-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0018_alter_adhesion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='droit_adhesions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affectation',
            name='droit_equipe',
            field=models.BooleanField(default=False, help_text="Voir l'onglet Equipe (qui a quels droits). N'autorise jamais a modifier les droits de qui que ce soit : cette action reste toujours reservee aux admins."),
        ),
        migrations.AddField(
            model_name='affectation',
            name='droit_exporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affectation',
            name='droit_gerer_produits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affectation',
            name='droit_parametres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affectation',
            name='droit_recharger_especes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='affectation',
            name='droit_suivi_especes',
            field=models.BooleanField(default=False),
        ),
    ]
