# Generated by Django 6.0.7 on 2026-08-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0019_affectation_droit_adhesions_affectation_droit_equipe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifAdhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Ce que l'etudiant lit pour choisir, ex. '1ere annee' ou 'Ancien eleve'.", max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_adhesion', to='caisse.pole')),
            ],
            options={
                'verbose_name': "tarif d'adhésion",
                'ordering': ['prix'],
            },
        ),
    ]
