# Generated by Django 6.0.7 on 2026-08-20 15:06

from django.db import migrations


def creer_tarifs_depuis_prix_existant(apps, schema_editor):
    Pole = apps.get_model("caisse", "Pole")
    TarifAdhesion = apps.get_model("caisse", "TarifAdhesion")
    for pole in Pole.objects.exclude(prix_adhesion__isnull=True):
        TarifAdhesion.objects.create(
            pole=pole, description="Tarif unique", prix=pole.prix_adhesion,
        )


def revenir_a_un_seul_tarif(apps, schema_editor):
    Pole = apps.get_model("caisse", "Pole")
    TarifAdhesion = apps.get_model("caisse", "TarifAdhesion")
    for pole in Pole.objects.all():
        premier = pole.tarifs_adhesion.order_by("prix").first()
        if premier:
            pole.prix_adhesion = premier.prix
            pole.save(update_fields=["prix_adhesion"])


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0020_tarifadhesion'),
    ]

    operations = [
        migrations.RunPython(creer_tarifs_depuis_prix_existant, revenir_a_un_seul_tarif),
    ]
