# Generated by Django 6.0.7 on 2026-08-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0021_migrer_prix_adhesion_vers_tarifs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pole',
            name='prix_adhesion',
        ),
    ]
