# Generated by Django 6.0.7 on 2026-08-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0022_remove_pole_prix_adhesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='droit_suivi_especes',
        ),
    ]
