# Generated by Django 6.0.7 on 2026-08-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0023_remove_affectation_droit_suivi_especes'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='droit_adhesion_especes',
            field=models.BooleanField(default=False),
        ),
    ]
