# Generated by Django 6.0.7 on 2026-08-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0024_affectation_droit_adhesion_especes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='retire',
            field=models.BooleanField(default=False, help_text='Produit qui n\'est plus vendu du tout : disparaît de la vente et de la gestion normale, déplacé dans l\'onglet "Retirés" (visible uniquement des admins, jamais des vendeurs). Différent de "Disponible", qui reste visible mais grisé sur l\'écran de vente.'),
        ),
    ]
